### ISSUE TITLE
Red rock example in browser

### ISSUE THREAD

**Issue by steve2007a** [connormanning/entwine-cesium-pages#3]
When accessing the red-rock url from another machine, the point dataset is visible on top of the background satellite imagery but is not synchronized with it. It cannot be zoomed, rotated etc. along with the background imagery.

(I need to access from another machine because of webgl problems in ubuntu)

The following error appears in the Chrome console:
include.preload.js:346 Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

There are no errors shown in the python http server log. The problem also occurs in Firefox.

Screenshot attached
![capture](https://cloud.githubusercontent.com/assets/10550812/19945006/0dbe0d9e-a136-11e6-8f0e-0a634979eb84.PNG)

**Comment by connormanning** [comment]
I might try to rebuild the Cesium library - maybe there was some issue there.  The bundled version in this repository is a bit old by now, considering the ongoing active development of the 3D-tiles branch.

Can you try checking the "disable cache" box in the network tab of Chrome, and then refresh - and see if the issue persists.  I've encountered a few library issues that were seemingly resolved by this.

Perhaps you could also try [this](http://stackoverflow.com/a/37270101/3606338) as a debugging step to verify that the problem is the script permission error you mentioned.

**Comment by connormanning** [comment]
Also, do you see this issue when accessing the publicly-hosted demo at http://cesium.entwine.io/?resource=red-rocks?

**Comment by steve2007a** [comment]
No issue at all with the  publicly-hosted demo at http://cesium.entwine.io/?
resource=red-rocks

**Comment by steve2007a** [comment]
Hi Connor

I'm running docker on Ubuntu 14.04 (trusty).

I'm accessing the ubuntu box from Chrome on Windows 10.

I tried both your suggestions (disable cache and command line args) and the problem is still occurring.

(The Chrome error still shows)

![capture](https://cloud.githubusercontent.com/assets/10550812/20115283/a016f5e4-a5ef-11e6-82d1-e13d6c3ee1c7.PNG)

**Comment by steve2007a** [comment]
Connor - those Chrome errors are a red-herring. They were coming from an Adblock script. I removed Adblock from Chrome. There are no console errors but the problem still persists: The point cloud image sits on top of the background cesium imagery but is not synchronized with it.

**Comment by steve2007a** [comment]
I'm linking to a screen capture video of what I'm seeing in the browser. Seeing it happen is probably an improvement on how I'm describing it !

https://sendvid.com/53jq7ule

**Comment by connormanning** [comment]
Ah yes, the video makes the problem clear.  So the issue is that the red-rocks dataset does not have properly set elevation values.  In the demo version, this was patched after-the-fact by manually modifying Cesium's transformation matrix in the 3D-tiles output.  However I neglected to replace the bad-elevation version of the file with a good one for the public instructions.

I have replaced it now, so please try re-running the `entwine build` step.  You'll want to add the `-f` flag to force a rewrite, or just delete your `entwine-cesium-pages/data/red-rocks` directory before running.

Sorry for the oversight, hopefully this works for you.

**Comment by steve2007a** [comment]
Excellent stuff Connor - works perfectly now.
Next step for me is to try it with my own data set..
Thanks again
Steve
